name: 'Generate matrix from pubspec.yaml action'
description: 'GitHub Action to generates a matrix of Dart and Flutter SDK versions from a pubspec.yaml file'
branding:
  icon: "triangle"
  color: "blue"
inputs:
  pubspec:
    description: 'The path to the pubspec.yaml file'
    required: false
    default: 'pubspec.yaml'
  channel:
    description: 'The Flutter channel to use when resolving the Flutter SDK version. Default: any'
    required: false
    default: 'any'
  platform:
    description: 'The platform to use when resolving the Flutter SDK version. Default: The runner operating system'
    required: false
    default: '${{ runner.os }}'
  strict:
    description: 'If true, the action will assert constraints on the Dart SDK version bundled with the Flutter SDK to ensure compatibility. Default: false'
    required: false
    default: "false"
outputs:
  matrix:
    description: 'The `matrix` data'
  releases:
    description:  'The `matrix.dart`` data'
  versions:
    description:  'The `matrix.flutter` data'
runs:
  using: 'node20'
  main: 'dist/index.js'
