# This is a test artifact that is used to generate a matrix of Flutter versions from a pubspec.yaml file.
# See https://dart.dev/tools/pub/pubspec#flutter-sdk-constraints

name: test

environment:
  sdk: ^3.2.0
  flutter: '>= 3.22.0'
