name: test

on:
  push:

jobs:
  pubspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - id: pubspec
      name: Generate matrix from pubspec.yaml
      uses: ./
      with:
        pubspec: 'pubspec.yaml'
    outputs:
      flutter: ${{ steps.pubspec.outputs.flutter }}

  test:
    needs: pubspec
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter: ${{fromJson(needs.pubspec.outputs.flutter)}}
    steps:
    - uses: flutter-actions/setup-flutter@v3
      with:
        version: ${{ matrix.flutter }}
        channel: stable
